version: "3"
services:

  miservicio_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nombre
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306  
    ports:
      - 3306:3306
  miservicio_php:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb:/var/www/html  
    expose:  
      - 80  
    ports:
      - 80:80  
    links:
      - miservicio_mysql
    command: "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo pdo_mysql && apachectl restart && tail -f /dev/null'"
  miservicio_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    links:
     - miservicio_mysql:db
